# Generated by Django 5.0.3 on 2024-04-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('page_count', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
                ('author_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=3, max_digits=5)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
