# Generated by Django 5.0.3 on 2024-04-15 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_author_category_book_cover_remove_book_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author_name',
        ),
    ]
